#version: '1.0'
#services:
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile  # Ваш Dockerfile для фронтенда
#    container_name: school-frontend
#    ports:
#      - "5173:5173"           # Порт, на котором будет доступно ваше фронтенд-приложение
#    volumes:
#      - .:/app
#      - node_modules:/app/node_modules
#    depends_on:
#      - spring-server         # Указание на зависимость от сервера
#    environment:
#      - VITE_API_URL=http://spring-server:8084
#    networks:
#      - app-network
#
#  spring-school-app:
#    image: astraklaus/spring-school-app  # Docker Hub образ вашего Spring-сервера
#    container_name: reserve-app
#    ports:
#      - "8084:8084"                # Проброс порта сервера наружу
#    networks:
#      - app-network
#    depends_on:
#      - postgres
#      - minio
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://school-db:5432/school
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.yaml
#
#volumes:
#  node_modules: